name: 'Build Artifact Uploader'
description: 'Zips and uploads the build artifact to S3'
inputs:
  aws-access-key-id:
    required: true
    description: 'AWS access key ID'
  aws-secret-access-key:
    required: true
    description: 'AWS secret access key'
  aws-region:
    required: true
    default: 'ap-south-1'
    description: 'AWS region'
  project-name:
    required: true
    description: 'Name of the project'
  s3-base-path:
    required: true
    description: 'Base S3 path for uploads'
  source-directory:
    required: false
    default: 'dist'
    description: 'Directory to zip and upload'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Zip and upload to S3
      shell: bash
      run: |
        ZIP_NAME="${{ inputs.project-name }}-${{ github.run_id }}-${{ github.run_number }}.zip"
        S3_BUILD_PATH="${{ inputs.s3-base-path }}/${{ inputs.project-name }}-${{ github.run_id }}/${ZIP_NAME}"
        echo "Zipping directory: ${{ inputs.source-directory }}"
        zip -r "${ZIP_NAME}" "${{ inputs.source-directory }}"
        aws s3 cp "${ZIP_NAME}" "${S3_BUILD_PATH}"
        echo "Artifact uploaded to: ${S3_BUILD_PATH}"