name: 'Build Artifact Downloader'
description: 'Downloads and extracts build artifacts from S3'
inputs:
  aws-role-arn:
    required: true
    description: "IAM Role ARN to assume via GitHub OIDC"
  aws-region:
    required: true
    default: 'ap-south-1'
    description: 'AWS region'
  project-name:
    required: true
    description: 'Name of the project used during upload'
  s3-base-path:
    required: true
    description: 'Base S3 path used during upload'
  target-directory:
    required: false
    default: './dist'
    description: 'Directory to extract the artifact'

runs:
  using: 'composite'
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v5
    with:
      role-to-assume: ${{ inputs.aws-role-arn }}
      aws-region: ${{ inputs.aws-region }}

  - name: Download and extract artifact
    shell: bash
    run: |
      ZIP_NAME="${{ inputs.project-name }}-${{ github.run_id }}-${{ github.run_number }}.zip"
      S3_SOURCE_PATH="${{ inputs.s3-base-path }}/${{ inputs.project-name }}-${{ github.run_id }}/${ZIP_NAME}"
      TARGET_DIR="${{ inputs.target-directory }}"

      echo "Downloading artifact from: ${S3_SOURCE_PATH}"
      aws s3 cp "${S3_SOURCE_PATH}" "${ZIP_NAME}"

      echo "Extracting to: ${TARGET_DIR}"
      mkdir -p "${TARGET_DIR}"
      unzip -o "${ZIP_NAME}" -d "${TARGET_DIR}"
      rm "${ZIP_NAME}"
