name: Build Docker Image
description: Builds and pushes a Docker image to AWS ECR.

inputs:
  AWS_ROLE_ARN:
    required: true
    description: "IAM Role ARN to assume via GitHub OIDC"
  AWS_REGION:
    required: true
    description: "AWS region for configuring AWS credentials."
  BRANCH_NAME:
    required: true
    description: "Branch executing workflow"
  ECR_REGISTRY:
    required: true
    description: "Amazon ECR registry URL."
  ECR_REPOSITORY:
    required: true
    description: "Amazon ECR repository name."
  DOCKERFILE_PATH:
    required: false
    default: './docker/Dockerfile'
    description: "Path to the Dockerfile for building the image."
  BUILD_CONTEXT:
    required: false
    default: '.'
    description: "The context for Docker build (default is the current directory)."
  PIP_MODULES_FILE:
    required: false
    default: './dependencies/requirements_gis.txt'
    description: "Path to the pip modules requirements file."
  APT_MODULES_FILE:
    required: false
    default: './dependencies/apt_requirements_gis.txt'
    description: "Path to the apt dependencies requirements file."
  IMAGE_TAG:
    required: false
    description: "Docker Image tag while pushing to ECR, default will be BRANCH NAME"
  GH_RAW_SSH_KEY:
    required: true
    description: "GIT_SSH Raw SSH key for cloning private repositories."

runs:
  using: 'composite'
  steps:
  - name: Copy Dependency Files
    shell: bash
    run: |
      if [ -n "${{ inputs.APT_MODULES_FILE }}" ]; then
        cp "${{ inputs.APT_MODULES_FILE }}" apt_requirements.txt
      fi

      if [ -n "${{ inputs.PIP_MODULES_FILE }}" ]; then
        cp "${{ inputs.PIP_MODULES_FILE }}" requirements.txt
      fi

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v5
    with:
      role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
      aws-region: ${{ inputs.AWS_REGION }}

  - name: Login to Amazon ECR
    uses: aws-actions/amazon-ecr-login@v2

  - name: Set IMAGE_TAG
    shell: bash
    run: |
      IMAGE_TAG="${{ inputs.IMAGE_TAG }}"
      if [[ -z "$IMAGE_TAG" ]]; then
        IMAGE_TAG="${{ inputs.BRANCH_NAME }}"
      fi
      echo "Using IMAGE_TAG: $IMAGE_TAG"
      echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 

  - name: Build Docker Image
    shell: bash
    run: |
      export RAW_GH_KEY=$(echo -n "${{ inputs.GH_RAW_SSH_KEY }}" | sed ':a;N;$!ba;s/\n/\\n/g')
      docker build -f ${{ inputs.DOCKERFILE_PATH }} \
        --build-arg "GIT_KEY=${RAW_GH_KEY}" \
        -t ${{ inputs.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:$IMAGE_TAG \
        ${{ inputs.BUILD_CONTEXT }}

  - name: Push Docker Image to ECR
    shell: bash
    run: |
      docker push ${{ inputs.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:$IMAGE_TAG
