name: Terragrunt Apply

on:
  workflow_call:
    inputs:
      working_dir:
        description: "Directory containing root terragrunt.hcl"
        required: false
        default: ${{ github.workspace }}
        type: string
      plan_file_name:
        description: "Enter Terragrunt Plan File name to run. If using s3 as artifact store pass s3 path here. Ex: naxa-ci-artifacts/some-prefix/plan"
        required: true
        type: string
      terraform_version:
        description: "Terraform Version"
        required: false
        default: "1.6.0"
        type: string
      opentofu_version:
        description: "Open Tofu Version"
        required: false
        default: "1.6.0"
        type: string
      terragrunt_version:
        description: "Terragrunt Version"
        required: false
        default: "0.54.12"
        type: string
      aws-use-oidc:
        description: "Prefer AWS OIDC auth"
        default: "true"
        type: string
      aws_region:
        description: "AWS Region"
        required: false
        default: "ap-south-1"
        type: string
      aws-access-key-id:
        description: "AWS_ACCESS_KEY_ID required if not aws-use-oidc"
        required: false
        type: string
      aws-secret-access-key:
        description: "AWS_SECRET_ACCESS_KEY required if not aws-use-oidc"
        required: false
        type: string
      use_gh_artifacts:
        description: "Use GitHub Artifacts to store plan file"
        required: false
        default: true
        type: boolean

env:
  AWS_REGION: ${{ inputs.aws_region }}
  tofu_version: ${{ inputs.opentofu_version }}
  tf_version: ${{ inputs.terraform_version }}
  tg_version: ${{ inputs.terragrunt_version }}
  working_dir: ${{ inputs.working_dir }}

jobs:
  apply:
    name: Apply Terragrunt Plan File
    runs-on: "ubuntu-latest"

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: naxa-developers/gh-workflows/.github/actions/configure_aws_credentials@master
        with:
          USE_OIDC_FOR_AWS: ${{inputs.aws-use-oidc }}
          AWS_CONFIG_FILE_PATH: ${{ github.workspace }}/.aws/credentials
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}

      - name: Get Plan form S3
        if: ${{ inputs.use_gh_artifacts == false }}
        run: |
          aws s3 cp s3://${{ inputs.plan_file_name }}.plan.out ${{ inputs.working_dir }}/${{ inputs.plan_file_name }}.plan.out

      - name: Get Plan from GitHub Artifacts
        if: ${{ inputs.use_gh_artifacts == true }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.plan_file_name }}
          path: ${{ inputs.working_dir }}

      - name: Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@v2
        env:
          AWS_SHARED_CREDENTIALS_FILE: ${{ github.workspace }}/.aws/credentials
          INPUT_PRE_EXEC_1: export TERRAGRUNT_GIT_REPO_NAME=${{ github.event.repository.name }}
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: apply ${{ inputs.plan_file_name }}.plan.out
